# Generated by Django 4.2.6 on 2023-10-20 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('duration', models.CharField(blank=True, default='', max_length=10)),
                ('rating', models.CharField(choices=[('G', 'General'), ('PG', 'Parental Guidance'), ('PG-13', 'Parents Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], default='G', max_length=20)),
                ('synopsis', models.TextField(default='', null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
