# Generated by Django 4.2.6 on 2023-10-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_synopsis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='added_by',
            new_name='user',
        ),
    ]
